In [1]:
import os
import qsprpred
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

import torch

from qsprpred.data import QSPRDataset, RandomSplit
from qsprpred.data.descriptors.fingerprints import MorganFP
import pandas as pd
from qsprpred.data.descriptors.sets import RDKitDescs

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/xgboost/core.py:377: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc >= 2.28) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(


In [2]:
def load_datasets(path):
    dataset = QSPRDataset.fromTableFile(
    filename=path,
    store_dir="dataset_outputs/A2AR/data",
    name="A2ARDataset",
    target_props=[{"name": "Y", "task": "SINGLECLASS", "th": [0.5]}],
    random_state=42,
    smiles_col = 'Drug',
    sep=','
    )
    dataset.prepareDataset(
    feature_calculators=[MorganFP(radius=2, nBits=1024)],
    recalculate_features=True,
    shuffle=False
    )
    from qsprpred.data.descriptors.sets import RDKitDescs
    
    rdkit_descs = RDKitDescs()
    
    dataset.addDescriptors([rdkit_descs])
    
    dataset.descriptorSets
    return dataset
    

In [3]:
import torch
import pandas as pd
from torch.utils.data import Dataset, DataLoader
from transformers import RobertaTokenizerFast, RobertaForMaskedLM, DataCollatorWithPadding
from sklearn.base import BaseEstimator, TransformerMixin

class SMILESDataset(Dataset):
    def __init__(self, smiles, tokenizer, max_len=128):
        self.smiles = smiles
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.smiles)

    def __getitem__(self, idx):
        smile = self.smiles[idx]
        encoding = self.tokenizer(smile, truncation=True, padding='max_length', max_length=self.max_len, return_tensors='pt')
        return encoding


class ChemBERTaTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, model_name="entropy/roberta_zinc_480m", max_len=128, batch_size=32, device=None):
        self.model_name = model_name
        self.max_len = max_len
        self.batch_size = batch_size
        self.device = device or ("cuda" if torch.cuda.is_available() else "cpu")
        self.model = RobertaForMaskedLM.from_pretrained(self.model_name).to(self.device)
        self.tokenizer = RobertaTokenizerFast.from_pretrained(self.model_name, max_len=self.max_len)
        self.collator = DataCollatorWithPadding(self.tokenizer, padding=True, return_tensors='pt')
        self.embedding_dim = None  # bude nastaven po fit()

    def fit(self, X, y=None):
        # Zjistíme embedding dimenzi na prvním SMILES
        smiles_dataset = SMILESDataset(X, self.tokenizer, max_len=self.max_len)
        dataloader = DataLoader(smiles_dataset, batch_size=1, collate_fn=self.collator)
        with torch.no_grad():
            for batch in dataloader:
                input_ids = batch['input_ids'].squeeze(1).to(self.device)
                attention_mask = batch['attention_mask'].squeeze(1).to(self.device)
                outputs = self.model(input_ids=input_ids, attention_mask=attention_mask, output_hidden_states=True)
                embedding = outputs[1][-1]  # poslední hidden state
                self.embedding_dim = embedding.shape[-1]
                break
        return self

    def transform(self, X):
        self.model.eval()
        smiles_dataset = SMILESDataset(X, self.tokenizer, max_len=self.max_len)
        dataloader = DataLoader(smiles_dataset, batch_size=self.batch_size, collate_fn=self.collator)
        embeddings_list = []

        with torch.no_grad():
            for batch in dataloader:
                input_ids = batch['input_ids'].squeeze(1).to(self.device)
                attention_mask = batch['attention_mask'].squeeze(1).to(self.device)
                outputs = self.model(input_ids=input_ids, attention_mask=attention_mask, output_hidden_states=True)
                full_embeddings = outputs[1][-1]
                embeddings = ((full_embeddings * attention_mask.unsqueeze(-1)).sum(1) / attention_mask.sum(-1).unsqueeze(-1))
                embeddings_list.append(embeddings)

        all_embeddings = torch.cat(embeddings_list, dim=0).cpu().numpy()
        column_names = [f"chemberta_{i}" for i in range(self.embedding_dim)]
        return pd.DataFrame(all_embeddings, columns=column_names)


In [4]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

X1_all = load_datasets("CK1/data/ck1_train_1")

X2_all = load_datasets("CK1/data/ck1_val_1")

X3_all = load_datasets("CK1/data/ck1_test_1")

transformer = ChemBERTaTransformer()
X_train_emb = transformer.fit_transform(X1_all.df["Drug"])
X_val_emb = transformer.transform(X2_all.df["Drug"])
X_test_emb = transformer.transform(X3_all.df["Drug"])


/tmp/ipykernel_6497/195630644.py:17: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  smile = self.smiles[idx]


In [5]:
X1_all.df.Y.sum()/X1_all.df.Y.count()

0.1864754098360656

In [6]:
import pandas as pd
X1_all.X = X1_all.X.reset_index(drop=True)
X_train_emb = X_train_emb.reset_index(drop=True)
X1_all.X = pd.concat([X1_all.X, X_train_emb], axis = 1)

In [7]:
X2_all.X = X2_all.X.reset_index(drop=True)
X_val_emb = X_val_emb.reset_index(drop=True)
X2_all.X = pd.concat([X2_all.X, X_val_emb], axis = 1)
X3_all.X = X3_all.X.reset_index(drop=True)
X_test_emb = X_test_emb.reset_index(drop=True)
X3_all.X = pd.concat([X3_all.X, X_test_emb], axis = 1)

In [8]:
X1 = X1_all.X
y1 = X1_all.y
X2 = X2_all.X
y2 = X2_all.y
X3 = X3_all.X
y3 = X3_all.y

In [9]:
display(X1.shape)

(488, 2002)

In [10]:
imp_mean = SimpleImputer(missing_values=pd.NA, strategy='mean')
X1 = imp_mean.fit_transform(X1)
X2 = imp_mean.transform(X2)
X3 = imp_mean.transform(X3)
scaler = StandardScaler()
scaler.fit(X1)
X1 = scaler.transform(X1)
X2 = scaler.transform(X2)
X3 = scaler.transform(X3)

In [11]:
pd.DataFrame(X1).columns[pd.DataFrame(X1).isna().any()].tolist()



[]

In [12]:
from sklearn.decomposition import PCA
pca = PCA(n_components=10)
X1 = pca.fit_transform(X1)
X2 = pca.transform(X2)
X3 = pca.transform(X3)
display(X1)


array([[  2.5161192 ,  -6.151463  ,  -8.366511  , ...,  -1.345859  ,
         -0.44985315,   1.6194475 ],
       [ -9.859426  , -11.045518  ,   0.9475052 , ...,  -0.65095985,
          0.9123891 ,  -0.5361799 ],
       [-14.141918  ,   0.43427503,  -6.316108  , ...,  -0.12052033,
          5.3449397 ,   6.715585  ],
       ...,
       [ 14.959804  ,  -5.99857   ,  -6.4033017 , ...,   2.38916   ,
         -4.531216  ,   4.2576256 ],
       [  0.87556636, -11.750251  ,  -9.756387  , ...,   0.9735739 ,
          8.307615  ,  -8.000566  ],
       [ -9.74294   , -10.716171  ,   1.2020547 , ...,   0.05237854,
          1.9520187 ,   0.58245695]], dtype=float32)

In [13]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(sampling_strategy=0.5, random_state=42)
X1, y1 = smote.fit_resample(X1, y1)
display(pd.DataFrame(X1))


,0,1,2,3,4,5,6,7,8,9
0,2.516119,-6.151463,-8.366511,-7.524187,-5.272499,3.254251,0.580053,-1.345859,-0.449853,1.619447
1,-9.859426,-11.045518,0.947505,7.024610,3.540941,-0.846933,16.123507,-0.650960,0.912389,-0.536180
2,-14.141918,0.434275,-6.316108,-3.726771,-0.609310,-2.591326,-2.445337,-0.120520,5.344940,6.715585
3,1.866864,-4.928765,-1.755543,3.479309,-3.916451,9.218805,1.004900,-2.431035,-4.941957,-6.393714
4,18.861074,10.574719,5.743189,2.777518,0.899291,-0.108476,10.990431,-8.192657,0.677484,-4.859463
...,...,...,...,...,...,...,...,...,...,...
590,-0.361228,-0.107648,-3.505981,-0.087660,16.784941,-4.424936,-13.850990,5.748617,7.224898,-1.544913
591,1.275798,-0.652351,-3.429251,-0.302536,16.278852,-3.513371,-14.500471,5.027085,7.166660,-1.036747
592,11.375955,-6.403400,-2.477593,1.300274,-2.784734,6.248819,-0.821540,3.774483,-5.005310,3.774700
593,-11.826805,9.276116,-3.257109,6.433682,-3.318424,-1.760713,1.178171,1.568496,13.990343,0.452569


In [14]:

# Přidejte cestu k vašemu lokálnímu repozitáři
import sys
import os

# Přidání cesty k lokálnímu repozitáři na začátek sys.path
sys.path.insert(0, '/home/ubuntu/Bakalarka/QSPRpred')

# Zkontrolujte, zda je cesta v sys.path
print(sys.path)

from importlib import reload

# Znovu proveďte import
from qsprpred.extra.gpu.models.neural_network import STFullyConnected
# Znovu načtěte modul, abyste zajistili, že je správně importován
reload(sys.modules['qsprpred.extra.gpu.models.neural_network'])

# Znovu proveďte import
from qsprpred.extra.gpu.models.neural_network import STFullyConnected

os.chdir('/home/ubuntu/Bakalarka/QSPRpred')
print(os.getcwd())


import sys
import importlib.util

# Přidání cesty k repozitáři do sys.path
sys.path.insert(0, '/home/ubuntu/Bakalarka/QSPRpred')

# Specifikujte cestu k souboru, který chcete importovat
module_path = '/home/ubuntu/Bakalarka/QSPRpred/qsprpred/extra/gpu/models/neural_network.py'
module_name = 'qsprpred.extra.gpu.models.neural_network'

# Načtěte modul z konkrétní cesty
spec = importlib.util.spec_from_file_location(module_name, module_path)
neural_network = importlib.util.module_from_spec(spec)
spec.loader.exec_module(neural_network)

# Nyní můžete používat třídu STFullyConnected
STFullyConnected = neural_network.STFullyConnected

['/home/ubuntu/Bakalarka/QSPRpred', '/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python311.zip', '/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11', '/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/lib-dynload', '', '/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages']
/home/ubuntu/Bakalarka/QSPRpred
lol


In [15]:
from sklearn.model_selection import ParameterGrid
from torch.nn import functional as F
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score, matthews_corrcoef
import pandas as pd

def test_fun(dic,  X_train, y_train, X_test, y_test) -> pd.DataFrame:
    param_grid_t = ParameterGrid(dic)
    i = 0
    val_f1_t = []
    val_acc_t = []
    val_mcc_t = []
    param_len_t = len(param_grid_t)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print("Device used:", device)
    for param in param_grid_t:
        i += 1
        print(i, '/', param_len_t)
        model_sts_t = STFullyConnected(n_dim=X_train.shape[1],  # počet vstupních neuronů (počet deskriptorů)
        n_class=1,  # regresní úloha (1 výstup)
        gpus=[],
        device=device,
        is_reg=False, **param)
        model_sts_t.fit(X_train, y_train)
        res = model_sts_t.predict(X_test)
        res = res >0.5
        val_f1_t.append(f1_score(res, y_test))
        val_acc_t.append(accuracy_score(res, y_test))
        val_mcc_t.append(matthews_corrcoef(res, y_test))
        print(param)
        print(f1_score(res, y_test))
        print(accuracy_score(res, y_test))
        print(matthews_corrcoef(res, y_test))
    my_df = pd.DataFrame(param_grid_t)
    my_df["F1"] = val_f1_t
    my_df["Acc"] = val_acc_t
    my_df["MCC"] = val_mcc_t
    return my_df

In [16]:
import optuna
from sklearn.metrics import f1_score, accuracy_score, matthews_corrcoef
import torch
import torch.nn.functional as F
import torch.optim as optim
from sklearn.metrics import confusion_matrix
def objective(trial, X_train, y_train, X_test, y_test):
    dropout_frac = trial.suggest_categorical("dropout_frac", [0, 0.1, 0.2, 0.4, 0.5, 0.6, 0.8, 0.9])
    patience = trial.suggest_categorical("patience", [10, 40, 75])
    tol = trial.suggest_categorical("tol", [1e-5, 1e-4, 1e-3, 1e-2, 0])
    weight_decay = trial.suggest_categorical("weight_decay", [1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 0])
    n_epochs = trial.suggest_categorical("n_epochs", [200, 300, 500, 1000])
    batch_size = trial.suggest_categorical("batch_size", [1024, 512, 256, 128, 64])
    optimizer = trial.suggest_categorical("optimizer", ["optim.AdamW", "optim.RMSprop"])
    lr = trial.suggest_categorical("lr", [1, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6])
    neuron_layers_dict = {
    '[4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8]': [4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8],
    '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]': [2048, 1024, 512, 256, 128, 64, 32, 16, 8],
    '[4096, 1024, 256, 64, 8]': [4096, 1024, 256, 64, 8],
    '[4096, 3072, 2048, 1536, 1024, 768, 512, 256, 128, 64, 32, 16, 8]': [4096, 3072, 2048, 1536, 1024, 768, 512, 256, 128, 64, 32, 16, 8],
    '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]': [4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096],
    '[200]': [200],
    '[2000]': [2000],
    '[2000, 1000]': [2000, 1000],
    '[2000, 1000, 500]': [2000, 1000, 500],
    '[1000, 50]': [1000, 50],
    '[4000, 2000]': [4000, 2000],
    '[4000, 2000, 1000, 500]': [4000, 2000, 1000, 500],
    '[4000, 2000, 2000, 500]': [4000, 2000, 2000, 500]
    }
    neuron_layers_size = trial.suggest_categorical("neuron_layers_size", list(neuron_layers_dict.keys()))
    opt = {"optim.AdamW": optim.AdamW,
           "optim.RMSprop": optim.RMSprop}
    
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(device)
    
    # Model
    model = STFullyConnected(
        n_dim=X_train.shape[1],
        n_class=1,
        gpus=[],
        device=device,
        is_reg=False,
        act_fun=F.selu,
        dropout_frac=dropout_frac,
        patience=patience,
        tol=tol,  # Opraveno: nyní používáme hodnotu z trial
        weight_decay=weight_decay,
        n_epochs=n_epochs,
        neuron_layers= neuron_layers_dict[neuron_layers_size],  # Použití neuron_layers_size
        batch_size=batch_size,
        optimizer=opt[optimizer],
        lr=lr,
        random_seed=69
    )
    # Trénink a predikce
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    preds_bin = preds > 0.5

    # Metiky
    f1 = f1_score(y_test, preds_bin)
    acc = accuracy_score(y_test, preds_bin)
    mcc = matthews_corrcoef(y_test, preds_bin)
    
    # Můžeš logovat i do trialu
    trial.set_user_attr("f1", f1)
    trial.set_user_attr("acc", acc)
    display(confusion_matrix(y_test, preds_bin))
    return mcc  # maximalizujeme MCC


In [17]:
display(X1)

array([[  2.5161192 ,  -6.151463  ,  -8.366511  , ...,  -1.345859  ,
         -0.44985315,   1.6194475 ],
       [ -9.859426  , -11.045518  ,   0.9475052 , ...,  -0.65095985,
          0.9123891 ,  -0.5361799 ],
       [-14.141918  ,   0.43427503,  -6.316108  , ...,  -0.12052033,
          5.3449397 ,   6.715585  ],
       ...,
       [ 11.375955  ,  -6.4034004 ,  -2.4775927 , ...,   3.7744832 ,
         -5.00531   ,   3.7746997 ],
       [-11.826805  ,   9.276116  ,  -3.257109  , ...,   1.5684965 ,
         13.990343  ,   0.45256945],
       [ -9.586394  , -10.694348  ,   1.8167986 , ...,  -0.9107799 ,
          1.0871527 ,   0.41879657]], dtype=float32)

In [ ]:
study_3 = optuna.create_study(
    study_name="CK1_study_bert_bceloss_earlystopping_pca_3",  # jméno pro pozdější načtení
    direction="maximize",
    sampler=optuna.samplers.RandomSampler(),
    storage="sqlite:///optuna_results.db",
    load_if_exists=True  # pokud už existuje, nepřepíše ji
)

# Spusť optimalizaci
study_3.optimize(
    lambda trial: objective(trial, X1, y1, X2, y2),
    n_trials=5000
)
print("Best MCC:", study_3.best_value)
print("Best parameters:", study_3.best_params)

# Pokud chceš F1 a ACC u nejlepšího modelu:
print("Best F1:", study_3.best_trial.user_attrs["f1"])
print("Best ACC:", study_3.best_trial.user_attrs["acc"])

[I 2025-05-03 11:05:42,423] Using an existing study with name 'CK1_study_bert_bceloss_earlystopping_pca_3' instead of creating a new one.


cuda


array([[104,  21],
       [ 15,  15]])

[I 2025-05-03 11:05:59,205] Trial 137 finished with value: 0.31061969325452465 and parameters: {'dropout_frac': 0.6, 'patience': 10, 'tol': 0.01, 'weight_decay': 0.01, 'n_epochs': 200, 'batch_size': 64, 'optimizer': 'optim.RMSprop', 'lr': 1e-06, 'neuron_layers_size': '[200]'}. Best is trial 83 with value: 0.43598508527235863.


cuda


array([[105,  20],
       [ 17,  13]])

[I 2025-05-03 11:06:26,925] Trial 138 finished with value: 0.26379790746474585 and parameters: {'dropout_frac': 0.4, 'patience': 10, 'tol': 0.01, 'weight_decay': 0.01, 'n_epochs': 1000, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 0.001, 'neuron_layers_size': '[200]'}. Best is trial 83 with value: 0.43598508527235863.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 11:07:10,722] Trial 139 finished with value: 0.0 and parameters: {'dropout_frac': 0.1, 'patience': 40, 'tol': 0.01, 'weight_decay': 1e-06, 'n_epochs': 1000, 'batch_size': 512, 'optimizer': 'optim.RMSprop', 'lr': 1, 'neuron_layers_size': '[4000, 2000]'}. Best is trial 83 with value: 0.43598508527235863.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 11:07:30,211] Trial 140 finished with value: 0.0 and parameters: {'dropout_frac': 0.5, 'patience': 10, 'tol': 1e-05, 'weight_decay': 0.0001, 'n_epochs': 200, 'batch_size': 128, 'optimizer': 'optim.RMSprop', 'lr': 0.01, 'neuron_layers_size': '[2000, 1000]'}. Best is trial 83 with value: 0.43598508527235863.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 11:08:12,751] Trial 141 finished with value: 0.0 and parameters: {'dropout_frac': 0.6, 'patience': 10, 'tol': 1e-05, 'weight_decay': 0.01, 'n_epochs': 500, 'batch_size': 128, 'optimizer': 'optim.RMSprop', 'lr': 0.001, 'neuron_layers_size': '[2000, 1000]'}. Best is trial 83 with value: 0.43598508527235863.


cuda


array([[105,  20],
       [ 10,  20]])

[I 2025-05-03 11:08:39,385] Trial 142 finished with value: 0.45746624172592293 and parameters: {'dropout_frac': 0.4, 'patience': 40, 'tol': 0.001, 'weight_decay': 0, 'n_epochs': 500, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 0.001, 'neuron_layers_size': '[1000, 50]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 11:08:49,303] Trial 143 finished with value: 0.0 and parameters: {'dropout_frac': 0.9, 'patience': 10, 'tol': 0, 'weight_decay': 0.1, 'n_epochs': 200, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 0.0001, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 11:10:51,148] Trial 144 finished with value: 0.0 and parameters: {'dropout_frac': 0.2, 'patience': 40, 'tol': 0.001, 'weight_decay': 1e-05, 'n_epochs': 500, 'batch_size': 64, 'optimizer': 'optim.AdamW', 'lr': 1, 'neuron_layers_size': '[4000, 2000, 2000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[109,  16],
       [ 17,  13]])

[I 2025-05-03 11:11:26,444] Trial 145 finished with value: 0.30931827625056946 and parameters: {'dropout_frac': 0.6, 'patience': 10, 'tol': 1e-05, 'weight_decay': 0.0001, 'n_epochs': 200, 'batch_size': 64, 'optimizer': 'optim.RMSprop', 'lr': 0.0001, 'neuron_layers_size': '[200]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 11:11:40,031] Trial 146 finished with value: 0.0 and parameters: {'dropout_frac': 0.5, 'patience': 10, 'tol': 0, 'weight_decay': 1e-06, 'n_epochs': 200, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 0.1, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[107,  18],
       [ 14,  16]])

[I 2025-05-03 11:11:53,503] Trial 147 finished with value: 0.37171071321470806 and parameters: {'dropout_frac': 0.5, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001, 'n_epochs': 300, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 0.0001, 'neuron_layers_size': '[4000, 2000]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 11:12:02,472] Trial 148 finished with value: 0.0 and parameters: {'dropout_frac': 0, 'patience': 75, 'tol': 0.01, 'weight_decay': 0.1, 'n_epochs': 200, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 0.1, 'neuron_layers_size': '[2000]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[113,  12],
       [ 19,  11]])

[I 2025-05-03 11:12:13,711] Trial 149 finished with value: 0.30081502522766856 and parameters: {'dropout_frac': 0.5, 'patience': 40, 'tol': 0, 'weight_decay': 0, 'n_epochs': 500, 'batch_size': 1024, 'optimizer': 'optim.RMSprop', 'lr': 1e-06, 'neuron_layers_size': '[2000, 1000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 11:12:35,307] Trial 150 finished with value: 0.0 and parameters: {'dropout_frac': 0, 'patience': 75, 'tol': 0.01, 'weight_decay': 0, 'n_epochs': 200, 'batch_size': 128, 'optimizer': 'optim.RMSprop', 'lr': 0.01, 'neuron_layers_size': '[2000, 1000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[104,  21],
       [ 13,  17]])

[I 2025-05-03 11:13:02,162] Trial 151 finished with value: 0.3661346485880381 and parameters: {'dropout_frac': 0.2, 'patience': 10, 'tol': 0.01, 'weight_decay': 1e-05, 'n_epochs': 200, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 11:14:52,746] Trial 152 finished with value: 0.0 and parameters: {'dropout_frac': 0.5, 'patience': 75, 'tol': 0.0001, 'weight_decay': 0.0001, 'n_epochs': 300, 'batch_size': 64, 'optimizer': 'optim.RMSprop', 'lr': 1, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[104,  21],
       [ 16,  14]])

[I 2025-05-03 11:15:10,930] Trial 153 finished with value: 0.282213473180223 and parameters: {'dropout_frac': 0, 'patience': 10, 'tol': 0.01, 'weight_decay': 0, 'n_epochs': 200, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[119,   6],
       [ 25,   5]])

[I 2025-05-03 11:15:28,636] Trial 154 finished with value: 0.18258571161934353 and parameters: {'dropout_frac': 0, 'patience': 10, 'tol': 0, 'weight_decay': 0.001, 'n_epochs': 300, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 0.001, 'neuron_layers_size': '[2000, 1000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[103,  22],
       [ 19,  11]])

[I 2025-05-03 11:18:32,136] Trial 155 finished with value: 0.18401512569492026 and parameters: {'dropout_frac': 0.8, 'patience': 40, 'tol': 0.01, 'weight_decay': 0, 'n_epochs': 1000, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 0.0001, 'neuron_layers_size': '[2000, 1000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[109,  16],
       [ 16,  14]])

[I 2025-05-03 11:20:20,120] Trial 156 finished with value: 0.33866666666666667 and parameters: {'dropout_frac': 0.1, 'patience': 40, 'tol': 0.0001, 'weight_decay': 0, 'n_epochs': 300, 'batch_size': 64, 'optimizer': 'optim.AdamW', 'lr': 1e-05, 'neuron_layers_size': '[4000, 2000]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[123,   2],
       [ 29,   1]])

[I 2025-05-03 11:21:24,327] Trial 157 finished with value: 0.04970674233862172 and parameters: {'dropout_frac': 0.1, 'patience': 40, 'tol': 0, 'weight_decay': 1e-06, 'n_epochs': 1000, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 1, 'neuron_layers_size': '[2000]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 11:22:48,190] Trial 158 finished with value: 0.0 and parameters: {'dropout_frac': 0, 'patience': 10, 'tol': 0.001, 'weight_decay': 0.01, 'n_epochs': 300, 'batch_size': 64, 'optimizer': 'optim.AdamW', 'lr': 1, 'neuron_layers_size': '[2000, 1000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 11:24:35,155] Trial 159 finished with value: 0.0 and parameters: {'dropout_frac': 0.2, 'patience': 75, 'tol': 0.01, 'weight_decay': 0, 'n_epochs': 200, 'batch_size': 64, 'optimizer': 'optim.AdamW', 'lr': 0.01, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 11:29:10,499] Trial 160 finished with value: 0.0 and parameters: {'dropout_frac': 0.1, 'patience': 40, 'tol': 0, 'weight_decay': 1e-05, 'n_epochs': 500, 'batch_size': 64, 'optimizer': 'optim.AdamW', 'lr': 1, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[109,  16],
       [ 18,  12]])

[I 2025-05-03 11:29:29,834] Trial 161 finished with value: 0.2793210473076928 and parameters: {'dropout_frac': 0.6, 'patience': 75, 'tol': 0.01, 'weight_decay': 0.1, 'n_epochs': 200, 'batch_size': 1024, 'optimizer': 'optim.RMSprop', 'lr': 1e-06, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[112,  13],
       [ 16,  14]])

[I 2025-05-03 11:30:04,684] Trial 162 finished with value: 0.37777777777777777 and parameters: {'dropout_frac': 0.2, 'patience': 40, 'tol': 1e-05, 'weight_decay': 0, 'n_epochs': 300, 'batch_size': 128, 'optimizer': 'optim.RMSprop', 'lr': 0.001, 'neuron_layers_size': '[200]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 11:30:42,544] Trial 163 finished with value: 0.0 and parameters: {'dropout_frac': 0.6, 'patience': 75, 'tol': 0, 'weight_decay': 0.001, 'n_epochs': 300, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 0.1, 'neuron_layers_size': '[4000, 2000, 2000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[112,  13],
       [ 18,  12]])

[I 2025-05-03 11:31:30,118] Trial 164 finished with value: 0.3179550040735082 and parameters: {'dropout_frac': 0.9, 'patience': 40, 'tol': 0.01, 'weight_decay': 1e-05, 'n_epochs': 300, 'batch_size': 128, 'optimizer': 'optim.RMSprop', 'lr': 1e-05, 'neuron_layers_size': '[2000, 1000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 11:31:57,432] Trial 165 finished with value: 0.0 and parameters: {'dropout_frac': 0.5, 'patience': 10, 'tol': 0.01, 'weight_decay': 0.0001, 'n_epochs': 200, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 0.1, 'neuron_layers_size': '[4000, 2000, 2000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 11:32:30,020] Trial 166 finished with value: 0.0 and parameters: {'dropout_frac': 0.4, 'patience': 40, 'tol': 0, 'weight_decay': 1e-06, 'n_epochs': 300, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 0.1, 'neuron_layers_size': '[4000, 2000, 2000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 11:32:58,161] Trial 167 finished with value: 0.0 and parameters: {'dropout_frac': 0.6, 'patience': 40, 'tol': 1e-05, 'weight_decay': 0.1, 'n_epochs': 200, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 0.001, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 11:33:21,748] Trial 168 finished with value: 0.0 and parameters: {'dropout_frac': 0.5, 'patience': 40, 'tol': 0.01, 'weight_decay': 0.0001, 'n_epochs': 200, 'batch_size': 512, 'optimizer': 'optim.RMSprop', 'lr': 0.01, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[104,  21],
       [ 12,  18]])

[I 2025-05-03 11:34:23,505] Trial 169 finished with value: 0.39331280199378404 and parameters: {'dropout_frac': 0.6, 'patience': 75, 'tol': 0.0001, 'weight_decay': 1e-05, 'n_epochs': 1000, 'batch_size': 512, 'optimizer': 'optim.RMSprop', 'lr': 1e-05, 'neuron_layers_size': '[4000, 2000]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 11:35:10,720] Trial 170 finished with value: 0.0 and parameters: {'dropout_frac': 0.8, 'patience': 75, 'tol': 0.01, 'weight_decay': 0.001, 'n_epochs': 1000, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 0.01, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[28, 97],
       [ 5, 25]])

[I 2025-05-03 11:35:24,976] Trial 171 finished with value: 0.05533321961455644 and parameters: {'dropout_frac': 0.1, 'patience': 40, 'tol': 0.0001, 'weight_decay': 0.01, 'n_epochs': 200, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 1, 'neuron_layers_size': '[4000, 2000]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[112,  13],
       [ 18,  12]])

[I 2025-05-03 11:35:49,003] Trial 172 finished with value: 0.3179550040735082 and parameters: {'dropout_frac': 0.2, 'patience': 75, 'tol': 0.01, 'weight_decay': 0.1, 'n_epochs': 500, 'batch_size': 1024, 'optimizer': 'optim.RMSprop', 'lr': 1e-05, 'neuron_layers_size': '[4000, 2000, 2000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 11:36:28,648] Trial 173 finished with value: 0.0 and parameters: {'dropout_frac': 0.2, 'patience': 75, 'tol': 0, 'weight_decay': 0.0001, 'n_epochs': 1000, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 1, 'neuron_layers_size': '[4000, 2000, 1000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 11:37:21,327] Trial 174 finished with value: 0.0 and parameters: {'dropout_frac': 0.9, 'patience': 75, 'tol': 0.0001, 'weight_decay': 0.001, 'n_epochs': 1000, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 0.0001, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[109,  16],
       [ 15,  15]])

[I 2025-05-03 11:40:55,443] Trial 175 finished with value: 0.3674234614174767 and parameters: {'dropout_frac': 0.5, 'patience': 75, 'tol': 0, 'weight_decay': 1e-06, 'n_epochs': 1000, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 1e-05, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[98, 27],
       [21,  9]])

[I 2025-05-03 11:41:06,263] Trial 176 finished with value: 0.07859052479933756 and parameters: {'dropout_frac': 0.9, 'patience': 75, 'tol': 0.01, 'weight_decay': 0.01, 'n_epochs': 200, 'batch_size': 1024, 'optimizer': 'optim.RMSprop', 'lr': 0.001, 'neuron_layers_size': '[4000, 2000]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[83, 42],
       [16, 14]])

[I 2025-05-03 11:43:54,136] Trial 177 finished with value: 0.1074654435100956 and parameters: {'dropout_frac': 0.9, 'patience': 75, 'tol': 0.001, 'weight_decay': 0.01, 'n_epochs': 500, 'batch_size': 128, 'optimizer': 'optim.RMSprop', 'lr': 0.0001, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[96, 29],
       [19, 11]])

[I 2025-05-03 11:44:21,105] Trial 178 finished with value: 0.12158971161662689 and parameters: {'dropout_frac': 0.5, 'patience': 10, 'tol': 0.01, 'weight_decay': 0, 'n_epochs': 300, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 0.0001, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[81, 44],
       [19, 11]])

[I 2025-05-03 11:44:32,385] Trial 179 finished with value: 0.012110601416389966 and parameters: {'dropout_frac': 0.9, 'patience': 40, 'tol': 0.001, 'weight_decay': 1e-06, 'n_epochs': 200, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 1, 'neuron_layers_size': '[1000, 50]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[108,  17],
       [ 15,  15]])

[I 2025-05-03 11:45:02,211] Trial 180 finished with value: 0.3552953082965788 and parameters: {'dropout_frac': 0.1, 'patience': 40, 'tol': 0.01, 'weight_decay': 0.0001, 'n_epochs': 500, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[4000, 2000, 2000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[107,  18],
       [ 14,  16]])

[I 2025-05-03 11:45:47,381] Trial 181 finished with value: 0.37171071321470806 and parameters: {'dropout_frac': 0.1, 'patience': 40, 'tol': 0.0001, 'weight_decay': 0.0001, 'n_epochs': 200, 'batch_size': 128, 'optimizer': 'optim.RMSprop', 'lr': 1e-05, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 11:46:06,426] Trial 182 finished with value: 0.0 and parameters: {'dropout_frac': 0.5, 'patience': 40, 'tol': 1e-05, 'weight_decay': 0.0001, 'n_epochs': 300, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 0.1, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 11:54:20,155] Trial 183 finished with value: 0.0 and parameters: {'dropout_frac': 0.8, 'patience': 75, 'tol': 0, 'weight_decay': 0.0001, 'n_epochs': 1000, 'batch_size': 64, 'optimizer': 'optim.RMSprop', 'lr': 0.001, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 11:55:04,010] Trial 184 finished with value: 0.0 and parameters: {'dropout_frac': 0.9, 'patience': 10, 'tol': 0.001, 'weight_decay': 1e-05, 'n_epochs': 300, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 1, 'neuron_layers_size': '[4000, 2000]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[82, 43],
       [13, 17]])

[I 2025-05-03 11:55:36,049] Trial 185 finished with value: 0.18060651552558227 and parameters: {'dropout_frac': 0.2, 'patience': 75, 'tol': 0.01, 'weight_decay': 0, 'n_epochs': 200, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[4096, 3072, 2048, 1536, 1024, 768, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 11:57:31,160] Trial 186 finished with value: 0.0 and parameters: {'dropout_frac': 0.2, 'patience': 10, 'tol': 1e-05, 'weight_decay': 0.001, 'n_epochs': 1000, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 0.001, 'neuron_layers_size': '[4000, 2000, 2000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[98, 27],
       [14, 16]])

[I 2025-05-03 11:58:18,968] Trial 187 finished with value: 0.28001937917433195 and parameters: {'dropout_frac': 0.1, 'patience': 75, 'tol': 1e-05, 'weight_decay': 1e-05, 'n_epochs': 300, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[124,   1],
       [ 30,   0]])

[I 2025-05-03 11:59:21,611] Trial 188 finished with value: -0.039477101697586135 and parameters: {'dropout_frac': 0.1, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.001, 'n_epochs': 1000, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 0.1, 'neuron_layers_size': '[2000, 1000]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 12:00:28,464] Trial 189 finished with value: 0.0 and parameters: {'dropout_frac': 0.1, 'patience': 75, 'tol': 0.01, 'weight_decay': 0.1, 'n_epochs': 500, 'batch_size': 512, 'optimizer': 'optim.RMSprop', 'lr': 0.1, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[96, 29],
       [14, 16]])

[I 2025-05-03 12:01:11,824] Trial 190 finished with value: 0.2622770016399181 and parameters: {'dropout_frac': 0.1, 'patience': 10, 'tol': 0.01, 'weight_decay': 0.01, 'n_epochs': 300, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 1e-05, 'neuron_layers_size': '[4000, 2000, 1000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[110,  15],
       [ 20,  10]])

[I 2025-05-03 12:01:56,125] Trial 191 finished with value: 0.22915675969261853 and parameters: {'dropout_frac': 0.1, 'patience': 75, 'tol': 0, 'weight_decay': 1e-05, 'n_epochs': 200, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 1e-06, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 12:02:47,626] Trial 192 finished with value: 0.0 and parameters: {'dropout_frac': 0.9, 'patience': 40, 'tol': 1e-05, 'weight_decay': 0.01, 'n_epochs': 500, 'batch_size': 512, 'optimizer': 'optim.RMSprop', 'lr': 0.0001, 'neuron_layers_size': '[4000, 2000, 2000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[102,  23],
       [ 14,  16]])

[I 2025-05-03 12:03:38,580] Trial 193 finished with value: 0.3180492411184303 and parameters: {'dropout_frac': 0.9, 'patience': 40, 'tol': 0, 'weight_decay': 0.0001, 'n_epochs': 300, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[1000, 50]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 12:04:50,402] Trial 194 finished with value: 0.0 and parameters: {'dropout_frac': 0.2, 'patience': 75, 'tol': 0, 'weight_decay': 0, 'n_epochs': 500, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 1, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 12:05:11,416] Trial 195 finished with value: 0.0 and parameters: {'dropout_frac': 0.5, 'patience': 75, 'tol': 0.01, 'weight_decay': 0.001, 'n_epochs': 300, 'batch_size': 512, 'optimizer': 'optim.RMSprop', 'lr': 0.1, 'neuron_layers_size': '[2000]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[114,  11],
       [ 17,  13]])

[I 2025-05-03 12:07:05,286] Trial 196 finished with value: 0.3771489177920147 and parameters: {'dropout_frac': 0.8, 'patience': 10, 'tol': 1e-05, 'weight_decay': 1e-06, 'n_epochs': 500, 'batch_size': 128, 'optimizer': 'optim.RMSprop', 'lr': 1e-05, 'neuron_layers_size': '[4000, 2000, 2000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[113,  12],
       [ 17,  13]])

[I 2025-05-03 12:07:17,273] Trial 197 finished with value: 0.362354126263953 and parameters: {'dropout_frac': 0.9, 'patience': 10, 'tol': 0.0001, 'weight_decay': 0.001, 'n_epochs': 200, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 0.001, 'neuron_layers_size': '[1000, 50]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 12:09:19,626] Trial 198 finished with value: 0.0 and parameters: {'dropout_frac': 0.2, 'patience': 40, 'tol': 1e-05, 'weight_decay': 0.1, 'n_epochs': 300, 'batch_size': 64, 'optimizer': 'optim.AdamW', 'lr': 0.001, 'neuron_layers_size': '[4000, 2000, 2000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[96, 29],
       [14, 16]])

[I 2025-05-03 12:10:41,155] Trial 199 finished with value: 0.2622770016399181 and parameters: {'dropout_frac': 0.6, 'patience': 75, 'tol': 0.0001, 'weight_decay': 0.0001, 'n_epochs': 1000, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 0.0001, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 12:11:56,919] Trial 200 finished with value: 0.0 and parameters: {'dropout_frac': 0.5, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.01, 'n_epochs': 1000, 'batch_size': 512, 'optimizer': 'optim.RMSprop', 'lr': 0.1, 'neuron_layers_size': '[4000, 2000, 2000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[112,  13],
       [ 22,   8]])

[I 2025-05-03 12:12:08,702] Trial 201 finished with value: 0.18778121925944147 and parameters: {'dropout_frac': 0.5, 'patience': 10, 'tol': 0.01, 'weight_decay': 0.01, 'n_epochs': 300, 'batch_size': 1024, 'optimizer': 'optim.RMSprop', 'lr': 0.1, 'neuron_layers_size': '[200]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[110,  15],
       [ 15,  15]])

[I 2025-05-03 12:16:26,081] Trial 202 finished with value: 0.38 and parameters: {'dropout_frac': 0.9, 'patience': 75, 'tol': 0.01, 'weight_decay': 0.0001, 'n_epochs': 1000, 'batch_size': 64, 'optimizer': 'optim.RMSprop', 'lr': 0.0001, 'neuron_layers_size': '[4000, 2000]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[103,  22],
       [ 21,   9]])

[I 2025-05-03 12:16:58,308] Trial 203 finished with value: 0.1224744871391589 and parameters: {'dropout_frac': 0.6, 'patience': 10, 'tol': 0.01, 'weight_decay': 1e-05, 'n_epochs': 300, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[200]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[ 14, 111],
       [  0,  30]])

[I 2025-05-03 12:17:26,618] Trial 204 finished with value: 0.15436899699759196 and parameters: {'dropout_frac': 0.9, 'patience': 40, 'tol': 1e-05, 'weight_decay': 1e-05, 'n_epochs': 500, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 12:17:44,116] Trial 205 finished with value: 0.0 and parameters: {'dropout_frac': 0.4, 'patience': 75, 'tol': 0.0001, 'weight_decay': 0.1, 'n_epochs': 200, 'batch_size': 1024, 'optimizer': 'optim.RMSprop', 'lr': 0.001, 'neuron_layers_size': '[4096, 3072, 2048, 1536, 1024, 768, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[113,  12],
       [ 18,  12]])

[I 2025-05-03 12:21:33,491] Trial 206 finished with value: 0.3320075415311944 and parameters: {'dropout_frac': 0.8, 'patience': 10, 'tol': 0, 'weight_decay': 1e-05, 'n_epochs': 1000, 'batch_size': 64, 'optimizer': 'optim.RMSprop', 'lr': 1e-05, 'neuron_layers_size': '[2000]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[108,  17],
       [ 21,   9]])

[I 2025-05-03 12:21:44,679] Trial 207 finished with value: 0.17341152311950356 and parameters: {'dropout_frac': 0.4, 'patience': 40, 'tol': 0.001, 'weight_decay': 0, 'n_epochs': 200, 'batch_size': 1024, 'optimizer': 'optim.RMSprop', 'lr': 0.0001, 'neuron_layers_size': '[2000]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 12:27:14,300] Trial 208 finished with value: 0.0 and parameters: {'dropout_frac': 0.6, 'patience': 40, 'tol': 0.0001, 'weight_decay': 0.1, 'n_epochs': 500, 'batch_size': 64, 'optimizer': 'optim.AdamW', 'lr': 1, 'neuron_layers_size': '[4096, 3072, 2048, 1536, 1024, 768, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 12:28:22,734] Trial 209 finished with value: 0.0 and parameters: {'dropout_frac': 0.8, 'patience': 40, 'tol': 0, 'weight_decay': 0.01, 'n_epochs': 500, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 0.01, 'neuron_layers_size': '[4096, 3072, 2048, 1536, 1024, 768, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[115,  10],
       [ 22,   8]])

[I 2025-05-03 12:28:39,806] Trial 210 finished with value: 0.23018969104459538 and parameters: {'dropout_frac': 0.4, 'patience': 40, 'tol': 1e-05, 'weight_decay': 0.0001, 'n_epochs': 200, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[4096, 3072, 2048, 1536, 1024, 768, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[110,  15],
       [ 14,  16]])

[I 2025-05-03 12:29:47,059] Trial 211 finished with value: 0.408248290463863 and parameters: {'dropout_frac': 0.8, 'patience': 75, 'tol': 0, 'weight_decay': 0.1, 'n_epochs': 500, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 1e-05, 'neuron_layers_size': '[2000, 1000]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[118,   7],
       [ 23,   7]])

[I 2025-05-03 12:30:24,189] Trial 212 finished with value: 0.2444175785795206 and parameters: {'dropout_frac': 0, 'patience': 75, 'tol': 1e-05, 'weight_decay': 1e-06, 'n_epochs': 300, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 0.01, 'neuron_layers_size': '[200]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 12:30:37,148] Trial 213 finished with value: 0.0 and parameters: {'dropout_frac': 0.1, 'patience': 40, 'tol': 0.0001, 'weight_decay': 0.01, 'n_epochs': 300, 'batch_size': 1024, 'optimizer': 'optim.RMSprop', 'lr': 0.1, 'neuron_layers_size': '[1000, 50]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[115,  10],
       [ 19,  11]])

[I 2025-05-03 12:31:25,036] Trial 214 finished with value: 0.3309259191867206 and parameters: {'dropout_frac': 0, 'patience': 10, 'tol': 0, 'weight_decay': 0.01, 'n_epochs': 200, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 1e-05, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 12:34:58,090] Trial 215 finished with value: 0.0 and parameters: {'dropout_frac': 0, 'patience': 75, 'tol': 0.01, 'weight_decay': 0.01, 'n_epochs': 1000, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 0.01, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[115,  10],
       [ 27,   3]])

[I 2025-05-03 12:35:45,257] Trial 216 finished with value: 0.028505573384448254 and parameters: {'dropout_frac': 0.8, 'patience': 10, 'tol': 0.01, 'weight_decay': 0.001, 'n_epochs': 500, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 12:36:17,029] Trial 217 finished with value: 0.0 and parameters: {'dropout_frac': 0.9, 'patience': 75, 'tol': 0, 'weight_decay': 1e-05, 'n_epochs': 300, 'batch_size': 1024, 'optimizer': 'optim.RMSprop', 'lr': 0.0001, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 12:43:20,742] Trial 218 finished with value: 0.0 and parameters: {'dropout_frac': 0.9, 'patience': 10, 'tol': 0, 'weight_decay': 1e-06, 'n_epochs': 1000, 'batch_size': 128, 'optimizer': 'optim.RMSprop', 'lr': 0.01, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 12:47:30,858] Trial 219 finished with value: 0.0 and parameters: {'dropout_frac': 0.8, 'patience': 75, 'tol': 0.01, 'weight_decay': 0, 'n_epochs': 1000, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 0.001, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 12:48:20,844] Trial 220 finished with value: 0.0 and parameters: {'dropout_frac': 0.9, 'patience': 10, 'tol': 0.01, 'weight_decay': 0.01, 'n_epochs': 1000, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 1, 'neuron_layers_size': '[200]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[109,  16],
       [ 16,  14]])

[I 2025-05-03 12:48:40,350] Trial 221 finished with value: 0.33866666666666667 and parameters: {'dropout_frac': 0.6, 'patience': 40, 'tol': 1e-05, 'weight_decay': 0.01, 'n_epochs': 500, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[4000, 2000]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[108,  17],
       [ 12,  18]])

[I 2025-05-03 12:50:19,401] Trial 222 finished with value: 0.43843878869070363 and parameters: {'dropout_frac': 0.5, 'patience': 75, 'tol': 0.001, 'weight_decay': 1e-06, 'n_epochs': 1000, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 0.0001, 'neuron_layers_size': '[4000, 2000]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 12:51:14,928] Trial 223 finished with value: 0.0 and parameters: {'dropout_frac': 0.1, 'patience': 75, 'tol': 0.01, 'weight_decay': 1e-05, 'n_epochs': 200, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 0.1, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 12:52:28,842] Trial 224 finished with value: 0.0 and parameters: {'dropout_frac': 0.2, 'patience': 10, 'tol': 0.0001, 'weight_decay': 0.001, 'n_epochs': 500, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 0.01, 'neuron_layers_size': '[2000, 1000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 12:53:08,367] Trial 225 finished with value: 0.0 and parameters: {'dropout_frac': 0.9, 'patience': 10, 'tol': 0.001, 'weight_decay': 1e-05, 'n_epochs': 300, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 0.001, 'neuron_layers_size': '[4096, 3072, 2048, 1536, 1024, 768, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 12:57:01,394] Trial 226 finished with value: 0.0 and parameters: {'dropout_frac': 0.4, 'patience': 75, 'tol': 0.001, 'weight_decay': 1e-05, 'n_epochs': 1000, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 0.01, 'neuron_layers_size': '[2000, 1000]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[106,  19],
       [ 15,  15]])

[I 2025-05-03 12:59:03,506] Trial 227 finished with value: 0.3322482744830096 and parameters: {'dropout_frac': 0.4, 'patience': 40, 'tol': 0.0001, 'weight_decay': 0.0001, 'n_epochs': 1000, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 1e-05, 'neuron_layers_size': '[4000, 2000, 1000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 13:03:09,456] Trial 228 finished with value: 0.0 and parameters: {'dropout_frac': 0.9, 'patience': 10, 'tol': 0.001, 'weight_decay': 0.001, 'n_epochs': 500, 'batch_size': 64, 'optimizer': 'optim.AdamW', 'lr': 0.01, 'neuron_layers_size': '[2000, 1000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 29,   1]])

[I 2025-05-03 13:04:48,481] Trial 229 finished with value: 0.16448792373994225 and parameters: {'dropout_frac': 0.4, 'patience': 10, 'tol': 0.001, 'weight_decay': 0.01, 'n_epochs': 500, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 0.1, 'neuron_layers_size': '[200]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  1, 124],
       [  0,  30]])

[I 2025-05-03 13:07:27,998] Trial 230 finished with value: 0.039477101697586135 and parameters: {'dropout_frac': 0.8, 'patience': 40, 'tol': 0.0001, 'weight_decay': 1e-05, 'n_epochs': 1000, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 1e-05, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 13:08:52,128] Trial 231 finished with value: 0.0 and parameters: {'dropout_frac': 0.1, 'patience': 75, 'tol': 0.01, 'weight_decay': 1e-05, 'n_epochs': 300, 'batch_size': 64, 'optimizer': 'optim.AdamW', 'lr': 0.1, 'neuron_layers_size': '[1000, 50]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[104,  21],
       [ 16,  14]])

[I 2025-05-03 13:10:25,262] Trial 232 finished with value: 0.282213473180223 and parameters: {'dropout_frac': 0.2, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.1, 'n_epochs': 300, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[4096, 3072, 2048, 1536, 1024, 768, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 13:12:50,347] Trial 233 finished with value: 0.0 and parameters: {'dropout_frac': 0.6, 'patience': 40, 'tol': 0, 'weight_decay': 1e-05, 'n_epochs': 1000, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 0.001, 'neuron_layers_size': '[4096, 3072, 2048, 1536, 1024, 768, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[108,  17],
       [ 15,  15]])

[I 2025-05-03 13:13:48,835] Trial 234 finished with value: 0.3552953082965788 and parameters: {'dropout_frac': 0.9, 'patience': 10, 'tol': 0.01, 'weight_decay': 1e-05, 'n_epochs': 300, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 1e-05, 'neuron_layers_size': '[4000, 2000, 2000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 13:14:07,301] Trial 235 finished with value: 0.0 and parameters: {'dropout_frac': 0.2, 'patience': 10, 'tol': 1e-05, 'weight_decay': 0.001, 'n_epochs': 200, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 0.001, 'neuron_layers_size': '[1000, 50]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[94, 31],
       [17, 13]])

[I 2025-05-03 13:14:18,317] Trial 236 finished with value: 0.16239824929226107 and parameters: {'dropout_frac': 0.9, 'patience': 75, 'tol': 0.001, 'weight_decay': 0.0001, 'n_epochs': 200, 'batch_size': 1024, 'optimizer': 'optim.RMSprop', 'lr': 0.001, 'neuron_layers_size': '[2000, 1000]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[103,  22],
       [ 13,  17]])

[I 2025-05-03 13:15:13,899] Trial 237 finished with value: 0.3556810215561072 and parameters: {'dropout_frac': 0.1, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.1, 'n_epochs': 300, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[111,  14],
       [ 23,   7]])

[I 2025-05-03 13:15:42,708] Trial 238 finished with value: 0.14006631928368174 and parameters: {'dropout_frac': 0.1, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001, 'n_epochs': 300, 'batch_size': 512, 'optimizer': 'optim.RMSprop', 'lr': 1e-05, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[110,  15],
       [ 15,  15]])

[I 2025-05-03 13:17:29,559] Trial 239 finished with value: 0.38 and parameters: {'dropout_frac': 0, 'patience': 40, 'tol': 0, 'weight_decay': 0, 'n_epochs': 1000, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[2000, 1000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 13:19:36,158] Trial 240 finished with value: 0.0 and parameters: {'dropout_frac': 0.4, 'patience': 40, 'tol': 0, 'weight_decay': 1e-06, 'n_epochs': 500, 'batch_size': 64, 'optimizer': 'optim.RMSprop', 'lr': 0.1, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 13:20:01,905] Trial 241 finished with value: 0.0 and parameters: {'dropout_frac': 0.8, 'patience': 40, 'tol': 1e-05, 'weight_decay': 0, 'n_epochs': 200, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 0.001, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 13:27:12,511] Trial 242 finished with value: 0.0 and parameters: {'dropout_frac': 0.5, 'patience': 75, 'tol': 0.0001, 'weight_decay': 0.001, 'n_epochs': 1000, 'batch_size': 64, 'optimizer': 'optim.RMSprop', 'lr': 1, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[124,   1],
       [ 30,   0]])

[I 2025-05-03 13:31:24,281] Trial 243 finished with value: -0.039477101697586135 and parameters: {'dropout_frac': 0.2, 'patience': 40, 'tol': 0, 'weight_decay': 0.01, 'n_epochs': 1000, 'batch_size': 128, 'optimizer': 'optim.RMSprop', 'lr': 0.001, 'neuron_layers_size': '[4000, 2000, 2000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[109,  16],
       [ 15,  15]])

[I 2025-05-03 13:31:42,364] Trial 244 finished with value: 0.3674234614174767 and parameters: {'dropout_frac': 0.4, 'patience': 10, 'tol': 1e-05, 'weight_decay': 0, 'n_epochs': 300, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[4000, 2000, 1000, 500]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


array([[106,  19],
       [ 15,  15]])

[I 2025-05-03 13:32:17,530] Trial 245 finished with value: 0.3322482744830096 and parameters: {'dropout_frac': 0, 'patience': 40, 'tol': 1e-05, 'weight_decay': 0.001, 'n_epochs': 200, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 1e-05, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 142 with value: 0.45746624172592293.


cuda


In [ ]:
study_3.best_trial

In [ ]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.device_count())


In [ ]:
import numpy as np
import pandas as pd

# Převod na DataFrame
X_final_train = pd.concat([pd.DataFrame(X1), pd.DataFrame(X2)], axis=0)
y_final_train = pd.concat([pd.DataFrame(y1), pd.DataFrame(y2)], axis=0)

# Pokud chceš mít je jako DataFrame s jedním sloupcem pro y


print(type(X_final_train))
print(type(y_final_train))

In [ ]:
model_final = STFullyConnected(
        n_dim=X1.shape[1],
        n_class=1,
        gpus=[],
        device="cuda",
        is_reg=False,
        act_fun=F.selu,
        dropout_frac=0.5,
        patience=75,
        tol=0.00001,  # Opraveno: nyní používáme hodnotu z trial
        weight_decay=0.01,
        n_epochs=300,
        neuron_layers= [200],  # Použití neuron_layers_size
        batch_size=512,
        optimizer=optim.RMSprop,
        lr=1e-5,
        random_seed=69
    )
model_final.fit(X1, y1)

In [ ]:
pred_test = model_final.predict(X3)
pred_test = pred_test > 0.5
print(matthews_corrcoef(pred_test, y3))
print(matthews_corrcoef(model_final.predict(X1) > 0.5, y1))

In [ ]:
from collections import Counter

print("Train:", Counter(y1))
print("Valid:", Counter(y2))
print("Test: ", Counter(y3))


In [ ]:
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import numpy as np

# Sloučení dat
X_all = np.concatenate([X1, X2, X3])
y_all = np.concatenate([['train'] * len(X1), ['val'] * len(X2), ['test'] * len(X3)])

# t-SNE transformace
X_tsne = TSNE(n_components=2, random_state=42).fit_transform(X_all)

# Barvy: 0 = train, 1 = val, 2 = test
colors = ["green" if l == 'train' else "yellow" if l == 'val' else "red" for l in y_all]

# Vykreslení
plt.figure(figsize=(8,6))
scatter = plt.scatter(X_tsne[:, 0], X_tsne[:, 1], c=colors, cmap='tab10', alpha=0.6)
plt.title("t-SNE: Train vs Val vs Test distribuce")
plt.xlabel("t-SNE dim 1")
plt.ylabel("t-SNE dim 2")
plt.legend(handles=scatter.legend_elements()[0], labels=['Train', 'Val', 'Test'])
plt.grid(True)
plt.show()
